-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 07:11:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbbook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbbook` DEFAULT CHARACTER SET utf8 ;
USE `dbbook` ;

-- -----------------------------------------------------
-- Table `dbbook`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbook`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbbook`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbook`.`libro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbbook`.`rel_user_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbbook`.`rel_libro_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` int not NULL,
  `libro_id` int not NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
